config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  get 'about', to: 'static_pages#about'
  get 'help', to: 'static_pages#help'
  get 'contact', to: 'static_pages#contact'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  resources :users do  
     member do
      get :following, :followers
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :posts do
    resources :comments, only:[:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]

  # http://localhost:3000/letter_opener/
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :active_relationships, class_name: 'Relationship', foreign_key: :follower_id, dependent: :destroy
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: :followed_id, dependent: :destroy
  has_many :following, through: 'active_relationships', source: 'followed'
  has_many :followers, through: 'passive_relationships', source: 'follower'
    
  attr_accessor :remember_token, :activation_token, :reset_token
  mount_uploader :image_name, ImageNameUploader
  before_save :downcase_email
  before_create :create_activation_digest
  
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: {minimum: 6},  allow_nil: true

  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためにユーザーをデータベースに記憶する(remember_digestカラムにremember_token(ランダムなトークン)のハッシュ値を保存)
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # ユーザーのログイン情報を破棄
  def forget
    update_attribute(:remember_digest, nil)
  end

  # 渡されたトークンが#{attribute}_digestにある(ハッシュ化された)tokenと一致したらtrueを返す
  def authenticated?(attribute, token)
    # sendメソッドに渡した引数を、そのオブジェクトのメソッドとして動的に活用できる
    digest = self.send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def activate
    update_attribute(:activated, true)
    update_attribute(:activated_at, Time.zone.now)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # パスワード再設定の属性を設定する
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # パスワード再設定のメールを送信する
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  # def feed
  #   Post.where("user_id = ?", self.id)
  # end

  def follow(other_user)
    self.active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    self.active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    self.following.include?(other_user)
  end

  private
  def downcase_email
    self.email = email.downcase
  end

  def create_activation_digest #→before_createで使用
    # acrivation_tokenの生成とactivation_digestへハッシュ化して追加
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(self.activation_token)
    # @user.activation_digest => ハッシュ値
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, except: [:show, :new, :create]
  before_action :correct_user, only: [:edit, :update]
  before_action :forbid_login_user, only: [:new, :create]
  before_action :admin_user, only: :destroy

  def index
    # ページ表示件数(デフォルトは30件)を「:per_page: 数」で指定可能
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email #user.rbに定義
      flash[:info] = "メールを確認してください"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "アカウントを編集しました"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "アカウントを削除しました"
    redirect_back(fallback_location: root_path)
  end

  def following
    @title = "フォロー"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "フォロワー"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end



  private

  def user_params
    params.require(:user).permit(:name, :email, :image_name, :password, :password_confirmation)
  end

  # 正しいユーザーかどうか確認
  def correct_user
    @user = User.find(params[:id])
    unless current_user?(@user)
      flash[:danger] = "権限がありません"
      redirect_to(root_path)
    end
  end

  def forbid_login_user
    if logged_in?
      flash[:danger] = "すでにログインしています"
      redirect_to root_path
    end
  end

  #adminカラムを付与後
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_with model: current_user.active_relationships.build do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォロー", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<div id="follow_form">
    <% if current_user.following?(@user) %>
        <%= render 'unfollow' %>
    <% else %>
        <%= render 'follow' %>
    <% end %>
</div>

app/views/users/_form.html.erb
<%= form_with model: @user, class: "form form-body users-form", local: true do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>

  <%= f.label :name, "ユーザーネーム" %>
  <%= f.text_field :name, value: @user.name %>

  <%= f.label :email, "メールアドレス" %>
  <%= f.text_field :email, value: @user.email %>

  <%= f.label :image_name, 'アイコン' %>
  <%= f.file_field :image_name %>

  <%= f.label :password, "パスワード" %>
  <%= f.password_field :password, value: @user.password %>

  <%= f.label :password_confirmation, "パスワード確認" %>
  <%= f.password_field :password_confirmation, value: @user.password_confirmation %>

  <%= f.submit value: "登録" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_with model: current_user.active_relationships.find_by(followed_id: @user.id), method: :delete do |f| %>
  <%= f.submit "フォロー中", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <div class="user-left">
    <span class="user-img">
      <% if user.image_name? %>
        <%= image_pack_tag user.image_name.url %>
      <% else %>
        <%= image_pack_tag "default_icon.jpeg" %>
      <% end %>
    </span>
  </div>

  <div class="user-right">
    <div class="user-name">
      <%= link_to user.name, user %>
      <% if current_user.admin? && !current_user?(user) %>
        <%# 管理ユーザーでかつ自分以外のユーザーに削除リンクを表示 %>
        | <%= link_to "削除", user, method: :delete, data: { confirm: "このユーザーを削除しますか？" } %>
      <% end %>
    </div>
  </div>
<li>

app/views/users/edit.html.erb
<div class="main">
  <div class="container">
    <div class="form-heading">アカウント編集</div>
    <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<div class="main">
  <div class="container">
    <h1 class="users-heading">ユーザー検索</h1>
    <ul class="users-index-item">
      <%= render @users %>
    </ul>
    <%= will_paginate %>
  </div>
</div>

app/views/users/new.html.erb
<div class="main">
  <div class="container">
    <div class="form-heading">アカウント登録</div>
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<div class="main user-show">
  <div class="container">

    <div class="user">
      <span class="user-img">
        <% if @user.image_name? %>
          <%= image_pack_tag @user.image_name.url %>
        <% else %>
          <%= image_pack_tag "default_icon.jpeg" %>
        <% end %>
      </span>
      <h2><%= @user.name %></h2>

      <% if current_user?(@user) %>
        <%= link_to "設定", edit_user_path(@user) %>
      <% else %>
        <%= render 'follow_form' if logged_in? %>
      <% end %>


      <%# フォロー・フォロワーの数 %>
      <div class="stats">
        <a href="<%= following_user_path(@user) %>">
          <strong id="following" class="stat">
            <%= @user.following.count %>
          </strong>
          フォロー
        </a>
        <a href="<%= followers_user_path(@user) %>">
          <strong id="followers" class="stat">
            <%= @user.followers.count %>
          </strong>
          フォロワー
        </a>
      </div>

    </div>



    <%# 投稿内容 %>
    <h3>投稿 (<%= @user.posts.count %>)</h3>
    <% if @user.posts.any? %>
      <ol class="posts-index-item">
        <%= render @posts %>
      </ol>
      <%= will_paginate @posts %>
    <% else %>
      <p class="">投稿がありません</p>
      <% if current_user?(@user) %>
        <a href="<%= new_post_path %>">供養する</a> 
      <% end %>
    <% end %>


    <%# いいねした投稿 %>

  </div>
</div>

app/views/users/show_follow.html.erb
<%# この部分はいずれshowの下部分に移動させる %>
<div class="main user-show">
    <div class="container">

        <div class="user">
            <span class="user-img">
                <% if @user.image_name? %>
                <%= image_pack_tag @user.image_name.url %>
                <% else %>
                <%= image_pack_tag "default_icon.jpeg" %>
                <% end %>
            </span>
            <h2><%= @user.name %></h2>

            <% if current_user?(@user) %>
                <%= link_to "設定", edit_user_path(@user) %>
            <% else %>
                <%= render 'follow_form' if logged_in? %>
            <% end %>


            <%# フォロー・フォロワーの数 %>
            <div class="stats">
                <a href="<%= following_user_path(@user) %>">
                <strong id="following" class="stat">
                    <%= @user.following.count %>
                </strong>
                フォロー
                </a>
                <a href="<%= followers_user_path(@user) %>">
                <strong id="followers" class="stat">
                    <%= @user.followers.count %>
                </strong>
                フォロワー
                </a>
            </div>

        </div>


        <%# フォロー・フォロワー %>
        <% if @users.any? %>
            <h3><%= @title %></h3>
            <ul class="users-index-item">
                <%= render @users %>
            </ul>
            <%= will_paginate %>
        <% end %>

    </div>
</div>