config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  get 'about', to: 'static_pages#about'
  get 'help', to: 'static_pages#help'
  get 'contact', to: 'static_pages#contact'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  resources :users do  
     member do
      get :following, :followers
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :posts do
    resources :comments, only:[:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]

  # http://localhost:3000/letter_opener/
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: {maximum: 200, message: "は200文字以内で入力してください"}
  validate :picture_size

  private

  def picture_size
    if picture.size > 1.megabytes
      errors.add(:picture, "1MB以内")
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, except: [:index]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @posts = Post.paginate(page: params[:page], per_page: 20)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:notice] = "投稿しました"
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      @post.touch
      flash[:notice] = "編集しました"
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    flash[:danger] = "削除しました"
    redirect_to root_path
  end

  
  private
  def post_params
    params.require(:post).permit(:content, :picture)
  end

  # 正しいユーザーかどうか確認
  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    if @post.user_id != @current_user.id
      flash[:danger] = "権限がありません"
      redirect_to root_path
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with model: @post, class: "form form-body posts-form", local: true do |f| %>
  <%= render 'layouts/error_messages', model: f.object  %>
  <%= f.text_area :content, value: @post.content %>
  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
  <%= f.submit value: "投稿" %>
<% end %>

<script type="text/javascript">
  $('#post_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/posts/_post.html.erb
<li>
    <div class="post-left">
        <span class="user-img">
            <% if post.user.image_name? %>
                <%= image_pack_tag post.user.image_name.url %>
            <% else %>
                <%= image_pack_tag "default_icon.jpeg" %>
            <% end %>
        </span>
    </div>

    <div class="post-right">
        <div class="post-user-name">
            <%= link_to post.user.name, "/users/#{post.user_id}" %>
        </div>

        <%= link_to post.content, post_path(post) %>
        <%= image_pack_tag post.picture.url if post.picture? %>

        <div class="post-time">
            <%= time_ago_in_words(post.created_at) %>前
        </div>
    </div>
</li>

app/views/posts/edit.html.erb
<div class="main posts-form">
  <div class="container">
    <h1 class="form-heading">Edit</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/posts/home.html.erb
<div class="home-main">
  <h2>Logical Diary</h2>
  
  <div class="home-message">
    <p>あなたもキレイな日記が書けるように</p>
  </div>
</div>

app/views/posts/index.html.erb
<div class="main">
    <div class="container">
        <% if @posts.any? %>
            <ol class="posts-index-item">
                <%= render @posts %>
            </ol>
            <%= will_paginate @posts %>
        <% end %>
    </div>
</div>

app/views/posts/new.html.erb
<div class="main posts-form">
  <div class="container">
    <h1 class="form-heading">Diary</h1>
    <%= render 'form' %>
  </div>
</div>

<%#= javascript_pack_tag 'form' %>
<%# <div id='form'></div> %>

app/views/posts/show.html.erb
<div class="main posts-show">
  <div class="container">
    <div class="posts-show-item">

      <div class="post-user-name">
        <span class="user-img">
          <% if @post.user.image_name? %>
            <%= image_pack_tag @post.user.image_name.url %>
          <% else %>
            <%= image_pack_tag "default_icon.jpeg" %>
          <% end %>
        </span>

        <%= link_to @post.user.name, "/users/#{@post.user_id}" %>
      </div>

      <p>
        <%= @post.content %>
        <%= image_pack_tag @post.picture.url if @post.picture? %>
      </p>

      
      <%# if Like.find_by(user_id: @current_user.id, post_id: @post.id) %>
        <%#= link_to("/likes/#{@post.id}/destroy", {method: "post"}) do %>
          <%# <span class="fa fa-heart like-btn-unlike"></span> %>
        <%# end %>
      <%# else %>
        <%#= link_to("/likes/#{@post.id}/create", {method: "post"}) do %>
          <%# <span class="fa fa-heart like-btn"></span> %>
        <%# end %>
      <%# end %>

      <%#= @likes_count %>

      <div class="post-option">

        <% if @post.user_id == @current_user.id %>
          <div class="post-menus">
            <%= link_to "編集", edit_post_path(@post) %>
            <%= link_to "削除", post_path(@post), method: :delete, data: {confirm: '投稿を削除しますか?'} %>
          </div>
        <% end %>
        <br/>

        <div class="post-time">
          <span>投稿 </span><%= @post.created_at.to_s(:datetime_jp) %>
          <br/>
          <% if @post.created_at != @post.updated_at%>
            <span>編集 </span><%= @post.updated_at.to_s(:datetime_jp) %>
          <% end %>
        </div>

      </div>

      <div>Comments</div>
      <% if @post.comments.any? %>
        <ul>
          <% @post.comments.each do |comment| %>
            <li>
              <%= comment.body %>
              <% if current_user?(@post.user) %>
                <%= link_to '削除', post_comment_path(@post, comment), method: :delete, data: { confirm: 'コメントを削除しますか?' }%>
              <% end %>
            </li>
          <% end %>
        </ul>
      <% end %>

      <%= form_for([@post, @post.comments.build]) do |f| %>
        <%= f.text_field :body%>
        <%= f.submit '投稿'%>
      <% end %>

    </div>
  </div>
</div>