config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  get 'about', to: 'static_pages#about'
  get 'help', to: 'static_pages#help'
  get 'contact', to: 'static_pages#contact'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  resources :users do  
     member do
      get :following, :followers
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :posts do
    resources :comments, only:[:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]

  # http://localhost:3000/letter_opener/
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <% model.errors.full_messages.each do |message| %>
    <div class="form-error">
      <%= message %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <ul>
    <li><%= link_to "Groovyについて", about_path %></li>
    <li><%= link_to "ヘルプ", help_path %></li>
    <li><%= link_to "お問い合わせ", contact_path %></li>
  </ul>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="header-logo">
    <%= link_to "The Groovy", root_path %>
  </div>

  <ul class="header-menus">
    <% if logged_in? %>
      <ul>
        <li><%= link_to "アイコン", current_user %></li>
        <li><%= link_to "投稿一覧",  posts_path %></li>
        <li><%= link_to "新規投稿", new_post_path %></li>
        <li><%= link_to "ユーザー一覧",  users_path %></li>
        <li><%= link_to "ログアウト", logout_path, class: 'command', data: { confirm: 'ログアウトしますか' }  %></li>
      </ul>
    <% else %>
      <ul>
        <li><%= link_to "ログイン", login_path %></li>
        <li><%= link_to "新規登録", signup_path %></li>
      </ul>
    <% end %>
  </ul>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="main">
      <% flash.each do |message_type, message| %>
        <div class="flash flash[<%= message_type %>]"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>